-- ----------------------------
-- Table structure for ODS_ENERGY_PAY_DATA
-- ----------------------------
CREATE TABLE "ODS_ENERGY_PAY_DATA" (
  "BUSI_MONTH" VARCHAR2(6 BYTE) NOT NULL ,
  "ENERGY_TYPE" VARCHAR2(20 BYTE) NOT NULL ,
  "ENERGY_AMOUNT" NUMBER(12,2) ,
  "TOTAL_AMOUNT" NUMBER(12,2) ,
  "INSERT_TIME" DATE ,
  "ENERGY_USAGE" NUMBER(12,2) ,
  "ENERGY_UNIT" VARCHAR2(10 BYTE)
);
COMMENT ON COLUMN "ODS_ENERGY_PAY_DATA"."BUSI_MONTH" IS '业务月份';
COMMENT ON COLUMN "ODS_ENERGY_PAY_DATA"."ENERGY_TYPE" IS '能源类型';
COMMENT ON COLUMN "ODS_ENERGY_PAY_DATA"."ENERGY_AMOUNT" IS '能源费用';
COMMENT ON COLUMN "ODS_ENERGY_PAY_DATA"."TOTAL_AMOUNT" IS '能源总费用';
COMMENT ON COLUMN "ODS_ENERGY_PAY_DATA"."INSERT_TIME" IS '插入时间';
COMMENT ON COLUMN "ODS_ENERGY_PAY_DATA"."ENERGY_USAGE" IS '能源用量';
COMMENT ON COLUMN "ODS_ENERGY_PAY_DATA"."ENERGY_UNIT" IS '能源单位';
COMMENT ON TABLE "ODS_ENERGY_PAY_DATA" IS '能源费用分析表';


-- ----------------------------
-- Table structure for ODS_ENERGY_USAGE_DATA
-- ----------------------------
CREATE TABLE "ODS_ENERGY_USAGE_DATA" (
  "BUSI_DATE" VARCHAR2(10 BYTE) ,
  "ENERGY_TYPE" VARCHAR2(20 BYTE) ,
  "ENERGY_AREA_ID" VARCHAR2(32 BYTE) ,
  "ENERGY_USAGE" NUMBER(12,2) ,
  "ENERGY_UNIT" VARCHAR2(10 BYTE) ,
  "HUNMAN_NUM" NUMBER(6) ,
  "AREAS" NUMBER(8,2) ,
  "INSERT_TIME" DATE
);
COMMENT ON COLUMN "ODS_ENERGY_USAGE_DATA"."BUSI_DATE" IS '业务日期';
COMMENT ON COLUMN "ODS_ENERGY_USAGE_DATA"."ENERGY_TYPE" IS '能源类型';
COMMENT ON COLUMN "ODS_ENERGY_USAGE_DATA"."ENERGY_AREA_ID" IS '所属区域ID';
COMMENT ON COLUMN "ODS_ENERGY_USAGE_DATA"."ENERGY_USAGE" IS '能源用量';
COMMENT ON COLUMN "ODS_ENERGY_USAGE_DATA"."ENERGY_UNIT" IS '单位';
COMMENT ON COLUMN "ODS_ENERGY_USAGE_DATA"."HUNMAN_NUM" IS '人数';
COMMENT ON COLUMN "ODS_ENERGY_USAGE_DATA"."AREAS" IS '面积';
COMMENT ON COLUMN "ODS_ENERGY_USAGE_DATA"."INSERT_TIME" IS '插入时间';

-- ----------------------------
-- Table structure for ODS_ENERGY_USETYPE_DATA
-- ----------------------------
CREATE TABLE "ODS_ENERGY_USETYPE_DATA" (
  "BUSI_MONTH" VARCHAR2(10 BYTE) ,
  "ENERGY_TYPE" VARCHAR2(10 BYTE) ,
  "ENERGY_TOTAL" NUMBER(12,2) ,
  "ENERGY_QUOTA" NUMBER(12,2) ,
  "ENERGY_AREA_ID" VARCHAR2(32 BYTE) ,
  "ENERGY_USAGE_TYPE" VARCHAR2(32 BYTE) ,
  "ENERGY_USAGE" NUMBER(12,2) ,
  "ENERGY_UNIT" VARCHAR2(10 BYTE) ,
  "INSERT_TIME" DATE
);
COMMENT ON COLUMN "ODS_ENERGY_USETYPE_DATA"."BUSI_MONTH" IS '业务月份';
COMMENT ON COLUMN "ODS_ENERGY_USETYPE_DATA"."ENERGY_TYPE" IS '能源类型';
COMMENT ON COLUMN "ODS_ENERGY_USETYPE_DATA"."ENERGY_TOTAL" IS '能源总用量';
COMMENT ON COLUMN "ODS_ENERGY_USETYPE_DATA"."ENERGY_QUOTA" IS '能源预警值';
COMMENT ON COLUMN "ODS_ENERGY_USETYPE_DATA"."ENERGY_AREA_ID" IS '所属区域单位D';
COMMENT ON COLUMN "ODS_ENERGY_USETYPE_DATA"."ENERGY_USAGE_TYPE" IS '能源使用类型';
COMMENT ON COLUMN "ODS_ENERGY_USETYPE_DATA"."ENERGY_USAGE" IS '能源使用类型用量';
COMMENT ON COLUMN "ODS_ENERGY_USETYPE_DATA"."ENERGY_UNIT" IS '能源单位';
COMMENT ON COLUMN "ODS_ENERGY_USETYPE_DATA"."INSERT_TIME" IS '插入时间';