spring:
  application:
    name: CoreApp
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB
  session:
    store-type: redis
  profiles:
    active: energy
  thymeleaf:
    enabled: false
  mvc:
    static-path-pattern: /**
    throw-exception-if-no-handler-found: true #出现错误时, 直接抛出异常
    async:
      request-timeout: 20000  #请求超时时间
  resources:
    add-mappings: false #关闭工程中的资源文件建立映射

#mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  typeAliasesPackage: com.jinxin.platform.**.domain #待实现通配符方式
  mapper-locations: classpath*:**/xml/*Mapper.xml
