INSERT INTO "ODS_MODEL_TYPE_CONFIG"("ID", "TYPE_NAME") VALUES ('1', '排行类模型');
INSERT INTO "ODS_MODEL_TYPE_CONFIG"("ID", "TYPE_NAME") VALUES ('2', '列表类模型');
INSERT INTO "ODS_MODEL_TYPE_CONFIG"("ID", "TYPE_NAME") VALUES ('3', '设备上报模型');
INSERT INTO "ODS_MODEL_TYPE_CONFIG"("ID", "TYPE_NAME") VALUES ('4', '趋势比较模型');


INSERT INTO "ODS_MODEL_CONFIG"("ID", "MODEL_NAME", "TYPE_ID") VALUES ('1', '设备报警排行', '1');
