CREATE TABLE "ODS_COMPARE_MODEL_DATA" (
  "ID" VARCHAR2(36 BYTE) NOT NULL ,
  "MODEL_ID" VARCHAR2(36 BYTE) NOT NULL ,
  "MONTH" VARCHAR2(11 BYTE) ,
  "VALUE" NUMBER(11) ,
  "UNIT" VARCHAR2(50 BYTE)
  );
COMMENT ON COLUMN "ODS_COMPARE_MODEL_DATA"."ID" IS 'id';
COMMENT ON COLUMN "ODS_COMPARE_MODEL_DATA"."MODEL_ID" IS '模型id';
COMMENT ON COLUMN "ODS_COMPARE_MODEL_DATA"."MONTH" IS '月份(格式如：2019-12)';
COMMENT ON COLUMN "ODS_COMPARE_MODEL_DATA"."VALUE" IS '数量';
COMMENT ON COLUMN "ODS_COMPARE_MODEL_DATA"."UNIT" IS '单位(数据单位，如：KW·h)';

CREATE TABLE "ODS_MONITOR_MODEL_DATA" (
  "ID" VARCHAR2(36 BYTE) NOT NULL ,
  "MODEL_ID" VARCHAR2(36 BYTE) NOT NULL ,
  "DEVICE_NAME" VARCHAR2(200 BYTE) NOT NULL ,
  "POSITION" VARCHAR2(200 BYTE) ,
  "STATUS" VARCHAR2(200 BYTE) ,
  "RTMP_URL" VARCHAR2(200 BYTE) NOT NULL ,
  "DEVICE_ID" VARCHAR2(36 BYTE) NOT NULL ,
  CONSTRAINT "SYS_C0010738" PRIMARY KEY ("ID")
)
COMMENT ON COLUMN "ODS_MONITOR_MODEL_DATA"."ID" IS 'id';
COMMENT ON COLUMN "ODS_MONITOR_MODEL_DATA"."MODEL_ID" IS '模型id';
COMMENT ON COLUMN "ODS_MONITOR_MODEL_DATA"."DEVICE_NAME" IS '设备名称';
COMMENT ON COLUMN "ODS_MONITOR_MODEL_DATA"."POSITION" IS '位置';
COMMENT ON COLUMN "ODS_MONITOR_MODEL_DATA"."STATUS" IS '1在线 0离线';
COMMENT ON COLUMN "ODS_MONITOR_MODEL_DATA"."RTMP_URL" IS '转换流地址';
COMMENT ON COLUMN "ODS_MONITOR_MODEL_DATA"."DEVICE_ID" IS '设备id'

CREATE TABLE "ODS_RANKING_MODEL_DATA" (
  "ID" VARCHAR2(36 BYTE) NOT NULL ,
  "NAME" VARCHAR2(200 BYTE) NOT NULL ,
  "VALUE" NUMBER(11) NOT NULL ,
  "MODEL_ID" VARCHAR2(36 BYTE) NOT NULL
);
COMMENT ON COLUMN "ODS_RANKING_MODEL_DATA"."ID" IS '主键id';
COMMENT ON COLUMN "ODS_RANKING_MODEL_DATA"."NAME" IS '名称';
COMMENT ON COLUMN "ODS_RANKING_MODEL_DATA"."VALUE" IS '数量';
COMMENT ON COLUMN "ODS_RANKING_MODEL_DATA"."MODEL_ID" IS '模型id';

CREATE TABLE "ODS_LIST_MODEL_DATA" (
  "MODEL_ID" VARCHAR2(32 BYTE) NOT NULL ,
  "COLUMN_1" VARCHAR2(64 BYTE) ,
  "COLUMN_2" VARCHAR2(64 BYTE) ,
  "COLUMN_3" VARCHAR2(64 BYTE) ,
  "COLUMN_4" VARCHAR2(64 BYTE) ,
  "COLUMN_5" VARCHAR2(64 BYTE) ,
  "COLUMN_6" VARCHAR2(64 BYTE) ,
  "COLUMN_7" VARCHAR2(64 BYTE) ,
  "COLUMN_8" VARCHAR2(64 BYTE) ,
  "COLUMN_9" VARCHAR2(64 BYTE) ,
  "COLUMN_10" VARCHAR2(64 BYTE) ,
  "COLUMN_11" NUMBER ,
  "COLUMN_12" NUMBER ,
  "COLUMN_13" NUMBER ,
  "COLUMN_14" NUMBER ,
  "COLUMN_15" DATE ,
  "COLUMN_16" DATE ,
  "INSERT_TIME" DATE NOT NULL
);
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."MODEL_ID" IS '报表模型id';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_1" IS '字符字段1';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_2" IS '字符字段2';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_3" IS '字符字段3';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_4" IS '字符字段4';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_5" IS '字符字段5';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_6" IS '字符字段6';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_7" IS '字符字段7';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_8" IS '字符字段8';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_9" IS '字符字段9';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_10" IS '字符字段10';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_11" IS '数值字段11';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_12" IS '数值字段12';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_13" IS '数值字段13';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_14" IS '数值字段14';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_15" IS '日期字段15';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_16" IS '日期字段16';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."INSERT_TIME" IS '数据插入时间';
COMMENT ON TABLE "ODS_LIST_MODEL_DATA" IS '报表模型数据表';


CREATE TABLE "ODS_LIST_MODEL_DATA_MAP" (
  "ID" VARCHAR2(36 BYTE) NOT NULL ,
  "MODEL_ID" VARCHAR2(255 BYTE) NOT NULL ,
  "COLUMN_ORI" VARCHAR2(255 BYTE) NOT NULL ,
  "COLUMN_EN" VARCHAR2(255 BYTE) NOT NULL ,
  "COLUMN_CN" VARCHAR2(255 BYTE)
);
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA_MAP"."ID" IS '主键id';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA_MAP"."MODEL_ID" IS '模型id';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA_MAP"."COLUMN_ORI" IS '原始列名';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA_MAP"."COLUMN_EN" IS '英文名';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA_MAP"."COLUMN_CN" IS '中文名';


CREATE TABLE "ODS_USER_CENTER_INFO" (
  "USER_ID" VARCHAR2(32 BYTE) NOT NULL ,
  "USER_NAME" VARCHAR2(64 BYTE) ,
  "ID_CARD" VARCHAR2(18 BYTE) ,
  "AGE" NUMBER(3) ,
  "GENDER" VARCHAR2(2 BYTE) ,
  "DEPT" VARCHAR2(64 BYTE) ,
  "PROV" VARCHAR2(32 BYTE) ,
  "CITY" VARCHAR2(32 BYTE) ,
  "USER_ADDRESS" VARCHAR2(32 BYTE) ,
  "REGIST_TIME" DATE ,
  "USER_CELLPHONE_NO" VARCHAR2(32 BYTE)
);
COMMENT ON COLUMN "ODS_USER_CENTER_INFO"."USER_ID" IS '用户ID';
COMMENT ON COLUMN "ODS_USER_CENTER_INFO"."USER_NAME" IS '用户姓名';
COMMENT ON COLUMN "ODS_USER_CENTER_INFO"."ID_CARD" IS '身份证号码';
COMMENT ON COLUMN "ODS_USER_CENTER_INFO"."AGE" IS '年龄';
COMMENT ON COLUMN "ODS_USER_CENTER_INFO"."GENDER" IS '性别 0-女 1-男 other-其他';
COMMENT ON COLUMN "ODS_USER_CENTER_INFO"."DEPT" IS '部门';
COMMENT ON COLUMN "ODS_USER_CENTER_INFO"."PROV" IS '省';
COMMENT ON COLUMN "ODS_USER_CENTER_INFO"."CITY" IS '市';
COMMENT ON COLUMN "ODS_USER_CENTER_INFO"."USER_ADDRESS" IS '区';
COMMENT ON COLUMN "ODS_USER_CENTER_INFO"."REGIST_TIME" IS '注册时间';
COMMENT ON COLUMN "ODS_USER_CENTER_INFO"."USER_CELLPHONE_NO" IS '电话号码';
COMMENT ON TABLE "ODS_USER_CENTER_INFO" IS '报表-用户中心信息表';


CREATE TABLE "ODS_DEVICE_CENTER_INFO" (
  "SERIAL_NUM" VARCHAR2(64 BYTE) NOT NULL ,
  "DEVICE_MAC" VARCHAR2(200 BYTE) ,
  "PRODUCT_CODE" VARCHAR2(200 BYTE) NOT NULL ,
  "REGIST_TIME" DATE NOT NULL ,
  "PROV" VARCHAR2(200 BYTE) ,
  "CITY" VARCHAR2(200 BYTE) ,
  "USER_ADDRESS" VARCHAR2(200 BYTE) ,
  "DEVICE_NAME" VARCHAR2(200 BYTE) ,
  "USER_CELLPHONE_NO" VARCHAR2(11 BYTE)
);
COMMENT ON COLUMN "ODS_DEVICE_CENTER_INFO"."SERIAL_NUM" IS '设备序列号';
COMMENT ON COLUMN "ODS_DEVICE_CENTER_INFO"."DEVICE_MAC" IS '设备mac';
COMMENT ON COLUMN "ODS_DEVICE_CENTER_INFO"."PRODUCT_CODE" IS '设备类型';
COMMENT ON COLUMN "ODS_DEVICE_CENTER_INFO"."REGIST_TIME" IS '注册时间';
COMMENT ON COLUMN "ODS_DEVICE_CENTER_INFO"."PROV" IS '省';
COMMENT ON COLUMN "ODS_DEVICE_CENTER_INFO"."CITY" IS '市';
COMMENT ON COLUMN "ODS_DEVICE_CENTER_INFO"."USER_ADDRESS" IS '地址';
COMMENT ON COLUMN "ODS_DEVICE_CENTER_INFO"."DEVICE_NAME" IS '设备名称';
COMMENT ON COLUMN "ODS_DEVICE_CENTER_INFO"."USER_CELLPHONE_NO" IS '用户电话号码';


CREATE TABLE "ODS_DEVICE_REPORT" (
  "SERIAL_NUM" VARCHAR2(200 BYTE) NOT NULL ,
  "DEVICE_MAC" VARCHAR2(200 BYTE) ,
  "PRODUCT_CODE" VARCHAR2(200 BYTE) NOT NULL ,
  "REPORT_TIME" DATE NOT NULL ,
  "MODEL_ID" VARCHAR2(200 BYTE) NOT NULL ,
  "DEVICE_NAME" VARCHAR2(200 BYTE) ,
  "CMD_NAME" VARCHAR2(200 BYTE)
);
COMMENT ON COLUMN "ODS_DEVICE_REPORT"."SERIAL_NUM" IS '设备序列号';
COMMENT ON COLUMN "ODS_DEVICE_REPORT"."DEVICE_MAC" IS '设备mac地址';
COMMENT ON COLUMN "ODS_DEVICE_REPORT"."PRODUCT_CODE" IS '设备类型';
COMMENT ON COLUMN "ODS_DEVICE_REPORT"."REPORT_TIME" IS '上报时间';
COMMENT ON COLUMN "ODS_DEVICE_REPORT"."MODEL_ID" IS '模型id';
COMMENT ON COLUMN "ODS_DEVICE_REPORT"."DEVICE_NAME" IS '设备名称';
COMMENT ON COLUMN "ODS_DEVICE_REPORT"."CMD_NAME" IS '上报类型';
