-- ----------------------------
-- Table structure for ODS_COMPARE_MODEL_DATA
-- ----------------------------
CREATE TABLE "ODS_COMPARE_MODEL_DATA" (
  "ID" VARCHAR2(36 BYTE) NOT NULL ,
  "MODEL_ID" VARCHAR2(36 BYTE) NOT NULL ,
  "MONTH" VARCHAR2(11 BYTE) ,
  "VALUE" NUMBER(11) ,
  "UNIT" VARCHAR2(50 BYTE)
);
COMMENT ON COLUMN "ODS_COMPARE_MODEL_DATA"."ID" IS 'id';
COMMENT ON COLUMN "ODS_COMPARE_MODEL_DATA"."MODEL_ID" IS '模型id';
COMMENT ON COLUMN "ODS_COMPARE_MODEL_DATA"."MONTH" IS '月份（格式如：2019-12）';
COMMENT ON COLUMN "ODS_COMPARE_MODEL_DATA"."VALUE" IS '数量';
COMMENT ON COLUMN "ODS_COMPARE_MODEL_DATA"."UNIT" IS '单位（数据单位，如：KW·h）';

-- ----------------------------
-- Table structure for ODS_DEVICE_REPORT_DATA
-- ----------------------------
CREATE TABLE "ODS_DEVICE_REPORT_DATA" (
  "SERIAL_NUM" VARCHAR2(36 BYTE) ,
  "NAME" VARCHAR2(255 BYTE) NOT NULL ,
  "VALUE" VARCHAR2(255 BYTE) NOT NULL ,
  "UNIT" VARCHAR2(255 BYTE) NOT NULL
);
COMMENT ON COLUMN "ODS_DEVICE_REPORT_DATA"."SERIAL_NUM" IS '设备序列号';
COMMENT ON COLUMN "ODS_DEVICE_REPORT_DATA"."NAME" IS '名称';
COMMENT ON COLUMN "ODS_DEVICE_REPORT_DATA"."VALUE" IS '值';
COMMENT ON COLUMN "ODS_DEVICE_REPORT_DATA"."UNIT" IS '单位';

-- ----------------------------
-- Table structure for ODS_KV_MODEL_DATA
-- ----------------------------
CREATE TABLE "ODS_KV_MODEL_DATA" (
  "ID" VARCHAR2(36 BYTE) NOT NULL ,
  "MODEL_ID" VARCHAR2(36 BYTE) NOT NULL ,
  "NAME" VARCHAR2(200 BYTE) NOT NULL ,
  "KEY" VARCHAR2(200 BYTE) NOT NULL ,
  "VALUE" VARCHAR2(200 BYTE) NOT NULL ,
  "REMARK" VARCHAR2(200 BYTE)
);
COMMENT ON COLUMN "ODS_KV_MODEL_DATA"."ID" IS '主键id';
COMMENT ON COLUMN "ODS_KV_MODEL_DATA"."MODEL_ID" IS '模型id';
COMMENT ON COLUMN "ODS_KV_MODEL_DATA"."NAME" IS '名称';
COMMENT ON COLUMN "ODS_KV_MODEL_DATA"."KEY" IS 'key';
COMMENT ON COLUMN "ODS_KV_MODEL_DATA"."VALUE" IS '值';
COMMENT ON COLUMN "ODS_KV_MODEL_DATA"."REMARK" IS '备注';

-- ----------------------------
-- Table structure for ODS_LAYOUT_CONFIG
-- ----------------------------
CREATE TABLE "ODS_LAYOUT_CONFIG" (
  "ID" VARCHAR2(36 BYTE) NOT NULL ,
  "USER_ID" VARCHAR2(36 BYTE) NOT NULL ,
  "LAYOUT" VARCHAR2(4000 BYTE) NOT NULL ,
  "UPDATE_TIME" DATE NOT NULL ,
  "CREATE_TIME" DATE NOT NULL ,
  "COL_NUM" VARCHAR2(200 BYTE) NOT NULL ,
  "STATUS" NUMBER(11) NOT NULL ,
  "REMARK" VARCHAR2(255 BYTE) ,
  "STYLE" VARCHAR2(2000 BYTE) ,
  "NAME" VARCHAR2(200 BYTE) ,
  "PROJECT" VARCHAR2(200 BYTE) ,
  "ORDER" NUMBER(11)
);
COMMENT ON COLUMN "ODS_LAYOUT_CONFIG"."ID" IS '主键id';
COMMENT ON COLUMN "ODS_LAYOUT_CONFIG"."USER_ID" IS '用户id';
COMMENT ON COLUMN "ODS_LAYOUT_CONFIG"."LAYOUT" IS '布局配置信息';
COMMENT ON COLUMN "ODS_LAYOUT_CONFIG"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "ODS_LAYOUT_CONFIG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "ODS_LAYOUT_CONFIG"."COL_NUM" IS '布局列数';
COMMENT ON COLUMN "ODS_LAYOUT_CONFIG"."STATUS" IS '状态（0 草稿，1 发布）';
COMMENT ON COLUMN "ODS_LAYOUT_CONFIG"."REMARK" IS '备注';
COMMENT ON COLUMN "ODS_LAYOUT_CONFIG"."STYLE" IS '布局风格';
COMMENT ON COLUMN "ODS_LAYOUT_CONFIG"."NAME" IS '配置名称';
COMMENT ON COLUMN "ODS_LAYOUT_CONFIG"."PROJECT" IS '所属项目';
COMMENT ON COLUMN "ODS_LAYOUT_CONFIG"."ORDER" IS '排序';

-- ----------------------------
-- Table structure for ODS_LINK_MODEL_DATA
-- ----------------------------
CREATE TABLE "ODS_LINK_MODEL_DATA" (
  "ID" VARCHAR2(36 BYTE) NOT NULL ,
  "MODEL_ID" VARCHAR2(36 BYTE) ,
  "NAME" VARCHAR2(255 BYTE) NOT NULL ,
  "LINK_URL" VARCHAR2(255 BYTE) NOT NULL
);
COMMENT ON COLUMN "ODS_LINK_MODEL_DATA"."ID" IS '主键id';
COMMENT ON COLUMN "ODS_LINK_MODEL_DATA"."MODEL_ID" IS '模型id';
COMMENT ON COLUMN "ODS_LINK_MODEL_DATA"."NAME" IS '名称';
COMMENT ON COLUMN "ODS_LINK_MODEL_DATA"."LINK_URL" IS '链接URL';

-- ----------------------------
-- Table structure for ODS_LIST_MODEL_DATA
-- ----------------------------
CREATE TABLE "ODS_LIST_MODEL_DATA" (
  "MODEL_ID" VARCHAR2(32 BYTE) NOT NULL ,
  "COLUMN_1" VARCHAR2(64 BYTE) ,
  "COLUMN_2" VARCHAR2(64 BYTE) ,
  "COLUMN_3" VARCHAR2(64 BYTE) ,
  "COLUMN_4" VARCHAR2(64 BYTE) ,
  "COLUMN_5" VARCHAR2(64 BYTE) ,
  "COLUMN_6" VARCHAR2(64 BYTE) ,
  "COLUMN_7" VARCHAR2(64 BYTE) ,
  "COLUMN_8" VARCHAR2(64 BYTE) ,
  "COLUMN_9" VARCHAR2(64 BYTE) ,
  "COLUMN_10" VARCHAR2(64 BYTE) ,
  "COLUMN_11" NUMBER ,
  "COLUMN_12" NUMBER ,
  "COLUMN_13" NUMBER ,
  "COLUMN_14" NUMBER ,
  "COLUMN_15" DATE ,
  "COLUMN_16" DATE ,
  "INSERT_TIME" DATE NOT NULL
);
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."MODEL_ID" IS '报表模型id';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_1" IS '字符字段1';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_2" IS '字符字段2';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_3" IS '字符字段3';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_4" IS '字符字段4';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_5" IS '字符字段5';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_6" IS '字符字段6';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_7" IS '字符字段7';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_8" IS '字符字段8';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_9" IS '字符字段9';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_10" IS '字符字段10';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_11" IS '数值字段11';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_12" IS '数值字段12';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_13" IS '数值字段13';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_14" IS '数值字段14';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_15" IS '日期字段15';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."COLUMN_16" IS '日期字段16';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA"."INSERT_TIME" IS '数据插入时间';
COMMENT ON TABLE "ODS_LIST_MODEL_DATA" IS '报表模型数据表';

-- ----------------------------
-- Table structure for ODS_LIST_MODEL_DATA_MAP
-- ----------------------------
CREATE TABLE "ODS_LIST_MODEL_DATA_MAP" (
  "ID" VARCHAR2(36 BYTE) NOT NULL ,
  "MODEL_ID" VARCHAR2(255 BYTE) NOT NULL ,
  "COLUMN_ORI" VARCHAR2(255 BYTE) NOT NULL ,
  "COLUMN_EN" VARCHAR2(255 BYTE) NOT NULL ,
  "COLUMN_CN" VARCHAR2(255 BYTE) NOT NULL ,
  "DATA_TYPE" NUMBER(11) DEFAULT 1  NOT NULL ,
  "SHOW_TYPE" NUMBER(11) DEFAULT 0  NOT NULL
);
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA_MAP"."ID" IS '主键id';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA_MAP"."MODEL_ID" IS '模型id';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA_MAP"."COLUMN_ORI" IS '原始列名';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA_MAP"."COLUMN_EN" IS '英文名';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA_MAP"."COLUMN_CN" IS '中文名';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA_MAP"."DATA_TYPE" IS '数据类型 (0：日期类型，1：其他)';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA_MAP"."SHOW_TYPE" IS '数据类型 (0：展示，1：不展示)';

-- ----------------------------
-- Table structure for ODS_LIST_MODEL_DATA_OPERATION
-- ----------------------------
CREATE TABLE "ODS_LIST_MODEL_DATA_OPERATION" (
  "ID" VARCHAR2(36 BYTE) NOT NULL ,
  "MODEL_ID" VARCHAR2(36 BYTE) NOT NULL ,
  "NAME" VARCHAR2(200 BYTE) NOT NULL ,
  "URL" VARCHAR2(200 BYTE) NOT NULL ,
  "METHOD" VARCHAR2(200 BYTE) NOT NULL ,
  "PARAM" VARCHAR2(200 BYTE)
);
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA_OPERATION"."ID" IS '主键id';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA_OPERATION"."MODEL_ID" IS '模型id';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA_OPERATION"."NAME" IS '名称';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA_OPERATION"."URL" IS '接口地址';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA_OPERATION"."METHOD" IS '请求方法';
COMMENT ON COLUMN "ODS_LIST_MODEL_DATA_OPERATION"."PARAM" IS '参数';

-- ----------------------------
-- Table structure for ODS_LIST_MODEL_VIEW
-- ----------------------------
CREATE TABLE "ODS_LIST_MODEL_VIEW" (
  "MODEL_ID" VARCHAR2(36 BYTE) NOT NULL ,
  "VIEW_NAME" VARCHAR2(36 BYTE) NOT NULL ,
  "REMARK" VARCHAR2(200 BYTE) ,
  "TYPE" VARCHAR2(255 BYTE)
);
COMMENT ON COLUMN "ODS_LIST_MODEL_VIEW"."MODEL_ID" IS '模型id';
COMMENT ON COLUMN "ODS_LIST_MODEL_VIEW"."VIEW_NAME" IS '视图名称';
COMMENT ON COLUMN "ODS_LIST_MODEL_VIEW"."REMARK" IS '备注';
COMMENT ON COLUMN "ODS_LIST_MODEL_VIEW"."TYPE" IS '表类型';

-- ----------------------------
-- Table structure for ODS_MODEL_CONFIG
-- ----------------------------
CREATE TABLE "ODS_MODEL_CONFIG" (
  "ID" VARCHAR2(36 BYTE) NOT NULL ,
  "MODEL_NAME" VARCHAR2(255 BYTE) NOT NULL ,
  "TYPE_ID" VARCHAR2(36 BYTE) NOT NULL
);
COMMENT ON COLUMN "ODS_MODEL_CONFIG"."ID" IS '主键id';
COMMENT ON COLUMN "ODS_MODEL_CONFIG"."MODEL_NAME" IS '模型名称';
COMMENT ON COLUMN "ODS_MODEL_CONFIG"."TYPE_ID" IS '模型类型id';

-- ----------------------------
-- Table structure for ODS_MODEL_TYPE_CONFIG
-- ----------------------------
CREATE TABLE "ODS_MODEL_TYPE_CONFIG" (
  "ID" VARCHAR2(36 BYTE) NOT NULL ,
  "TYPE_NAME" VARCHAR2(200 BYTE) NOT NULL
);
COMMENT ON COLUMN "ODS_MODEL_TYPE_CONFIG"."ID" IS '主键id';
COMMENT ON COLUMN "ODS_MODEL_TYPE_CONFIG"."TYPE_NAME" IS '类型名称';

-- ----------------------------
-- Table structure for ODS_MONITOR_MODEL_DATA
-- ----------------------------
CREATE TABLE "ODS_MONITOR_MODEL_DATA" (
  "ID" VARCHAR2(36 BYTE) NOT NULL ,
  "DEVICE_NAME" VARCHAR2(200 BYTE) NOT NULL ,
  "POSITION" VARCHAR2(200 BYTE) ,
  "STATUS" NUMBER(7) ,
  "RTMP" VARCHAR2(200 BYTE) ,
  "RTSP" VARCHAR2(200 BYTE) NOT NULL ,
  "DEVICE_NUM" VARCHAR2(36 BYTE)
);
COMMENT ON COLUMN "ODS_MONITOR_MODEL_DATA"."ID" IS 'id';
COMMENT ON COLUMN "ODS_MONITOR_MODEL_DATA"."DEVICE_NAME" IS '设备名称';
COMMENT ON COLUMN "ODS_MONITOR_MODEL_DATA"."POSITION" IS '位置';
COMMENT ON COLUMN "ODS_MONITOR_MODEL_DATA"."STATUS" IS '1在线 0离线';
COMMENT ON COLUMN "ODS_MONITOR_MODEL_DATA"."RTMP" IS '转换流地址';
COMMENT ON COLUMN "ODS_MONITOR_MODEL_DATA"."RTSP" IS '设备原始流地址';
COMMENT ON COLUMN "ODS_MONITOR_MODEL_DATA"."DEVICE_NUM" IS '设备序列号';

-- ----------------------------
-- Table structure for ODS_RANKING_MODEL_DATA
-- ----------------------------
CREATE TABLE "ODS_RANKING_MODEL_DATA" (
  "ID" VARCHAR2(36 BYTE) NOT NULL ,
  "NAME" VARCHAR2(200 BYTE) NOT NULL ,
  "VALUE" NUMBER(11) NOT NULL ,
  "MODEL_ID" VARCHAR2(36 BYTE) NOT NULL
);
COMMENT ON COLUMN "ODS_RANKING_MODEL_DATA"."ID" IS '主键id';
COMMENT ON COLUMN "ODS_RANKING_MODEL_DATA"."NAME" IS '名称';
COMMENT ON COLUMN "ODS_RANKING_MODEL_DATA"."VALUE" IS '数量';
COMMENT ON COLUMN "ODS_RANKING_MODEL_DATA"."MODEL_ID" IS '模型id';
